FootballWebApp/Models/match.cs
namespace FootballWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public match()
        {
            goals = new HashSet<goal>();
            red_cards = new HashSet<red_cards>();
            yellow_cards = new HashSet<yellow_cards>();
            TeamMatches = new HashSet<TeamMatch>();
        }

        [Key]
        public int match_id { get; set; }
        [Display(Name ="Team 1 Goals")]
        public int team1_score { get; set; }

        [Display(Name ="Team 2 Goals")]
        public int team2_score { get; set; }

        [StringLength(50)]
        [Display(Name ="Date")]
        [Required]
        public string date { get; set; }

        [StringLength(50)]
        [Required]
        [Display(Name ="Match Status")]
        public string status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goal> goals { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<red_cards> red_cards { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yellow_cards> yellow_cards { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatch> TeamMatches { get; set; }
    }
}

FootballWebApp/Controllers/goalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FootballWebApp.Models;

namespace FootballWebApp.Controllers
{
    [Authorize]
    public class goalsController : Controller
    {
        private FootballDB db = new FootballDB();

        // GET: goals
        /*public ActionResult Index()
        {
            var goals = db.goals.Include(g => g.match).Include(g => g.player);
            return View(goals.ToList());
        }*/

        // GET: goals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            goal goal = db.goals.Find(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }

        // GET: goals/Create
        public ActionResult Create(int id)
        {

            var selectedMatch = db.TeamMatches.Where(a => a.match_id == id);
            var team1 = selectedMatch.First(x => x.home_Away == "home").team;
            var team2 = selectedMatch.First(x => x.home_Away == "away").team;
            var players1 = team1.players.Where(a => a.team_id == team1.team_id);
            var players2 = team2.players.Where(a => a.team_id == team2.team_id);
            ViewBag.players1 = players1;
            ViewBag.players2 = players2;
            ViewBag.team1 = selectedMatch.First(x => x.home_Away == "home").team;
            ViewBag.team2 = selectedMatch.First(x => x.home_Away == "away").team;
            ViewBag.match_id = id;
            return View();
        }

        // POST: goals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "goal_id,match_id")] goal goal, int player_id1, int player_id2)
        {
            if (ModelState.IsValid)
            {
                if (player_id1 != 0)
                {
                    goal.player_id = player_id1;
                }
                else if (player_id2 != 0)
                {
                    goal.player_id = player_id2;
                }
                var teams = db.TeamMatches.Where(a => a.match_id == goal.match_id);

                db.goals.Add(goal);
                foreach (var item in teams)
                {
                    if (item.team.team_id == db.players.Find(goal.player_id).team_id)
                    {

                        item.team.goals_for++;
                        var match = db.matches.First(a => a.match_id == goal.match_id);
                        if (item.home_Away == "home")
                        {
                            match.team1_score++;
                        }
                        else if (item.home_Away == "away")
                        {
                            match.team2_score++;
                        }
                    }
                    else
                    {
                        item.team.goals_against++;
                    }

                }
                db.SaveChanges();
                return RedirectToAction("Index", "matches");
            }

            var selectedMatch = db.TeamMatches.Where(a => a.match_id == goal.match_id);
            var team1 = selectedMatch.First(x => x.home_Away == "home").team;
            var team2 = selectedMatch.First(x => x.home_Away == "away").team;
            var players1 = team1.players.Where(a => a.team_id == team1.team_id);
            var players2 = team2.players.Where(a => a.team_id == team2.team_id);
            ViewBag.players1 = players1;
            ViewBag.players2 = players2;
            ViewBag.team1 = selectedMatch.First(x => x.home_Away == "home").team;
            ViewBag.team2 = selectedMatch.First(x => x.home_Away == "away").team;

            return View(goal);
        }

        // GET: goals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            goal goal = db.goals.Find(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            ViewBag.match_id = new SelectList(db.matches, "match_id", "date", goal.match_id);
            ViewBag.player_id = new SelectList(db.players, "player_id", "fullname", goal.player_id);
            return View(goal);
        }

        // POST: goals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "goal_id,match_id,player_id")] goal goal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(goal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.match_id = new SelectList(db.matches, "match_id", "date", goal.match_id);
            ViewBag.player_id = new SelectList(db.players, "player_id", "fullname", goal.player_id);
            return View(goal);
        }

        // GET: goals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            goal goal = db.goals.Find(id);
            if (goal == null)
            {
                return HttpNotFound();
            }
            return View(goal);
        }

        // POST: goals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            goal goal = db.goals.Find(id);
            db.goals.Remove(goal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FootballWebApp/Controllers/matchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FootballWebApp.Models;

namespace FootballWebApp.Controllers
{
    [Authorize]
    public class matchesController : Controller
    {
        private FootballDB db = new FootballDB();

        // GET: matches
        public ActionResult Index()
        {
            return View(db.matches.ToList());
        }

        // GET: matches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            match match = db.matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            return View(match);
        }

        // GET: matches/Create
        public ActionResult Create(int? id)
        {
            var selectedTeams = id != null ? db.teams.Where(t => t.league_id == id) : db.teams;
            ViewBag.league_id = new SelectList(db.leagues.ToList(), "league_id", "name");
            if(id != null)
            {
                ViewBag.league_id = new SelectList(db.leagues.ToList(), "league_id", "name", id);
            }
            ViewBag.team1 = new SelectList(selectedTeams, "team_id", "name");
            ViewBag.team2 = new SelectList(selectedTeams, "team_id", "name");
            return View();
        }

        // POST: matches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "match_id,date,status")] match match, int team1, int team2, int league_id)
        {
            TeamMatch teamMatch1 = new TeamMatch();
            TeamMatch teamMatch2 = new TeamMatch();
            if (ModelState.IsValid)
            {
                teamMatch1.match_id = match.match_id;
                teamMatch1.team_id = team1;
                teamMatch1.home_Away = "home";
                db.TeamMatches.Add(teamMatch1);
                teamMatch2.match_id = match.match_id;
                teamMatch2.team_id = team2;
                teamMatch2.home_Away = "away";
                db.TeamMatches.Add(teamMatch2);
                match.team1_score = 0;
                match.team2_score = 0;
                db.matches.Add(match);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var selectedTeams = league_id != null ? db.teams.Where(t => t.league_id == league_id) : db.teams;
            ViewBag.league_id = new SelectList(db.leagues.ToList(), "league_id", "name");
            if (league_id != null)
            {
                ViewBag.league_id = new SelectList(db.leagues.ToList(), "league_id", "name", league_id);
            }
            ViewBag.team1 = new SelectList(selectedTeams, "team_id", "name");
            ViewBag.team2 = new SelectList(selectedTeams, "team_id", "name");
            return View(match);
        }

        // GET: matches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            match match = db.matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            ViewBag.team1 = match.TeamMatches.First(m => m.match_id == match.match_id);
            ViewBag.team2 = match.TeamMatches.Last(m => m.match_id == match.match_id);
            return View(match);
        }

        // POST: matches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "match_id,date,status")] match match)
        {
            if (ModelState.IsValid)
            {
                db.Entry(match).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(match);
        }

        // GET: matches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            match match = db.matches.Find(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            return View(match);
        }

        // POST: matches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            match match = db.matches.Find(id);
            db.matches.Remove(match);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FootballWebApp/Views/matches/Create.cshtml
@model FootballWebApp.Models.match

@{
    ViewBag.Title = "Create a match";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
}

<h2>Create a match</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label class="control-label col-md-2" for="league_id">Select a league</label>
        <div class="col-md-10">
            @Html.DropDownList("league_id", null, "Select a league", htmlAttributes: new { @class = "form-control", id = "league_id" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamMatches, "Home", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("team1", null, "Select the first club", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeamMatches, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamMatches, "Away", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("team2", null, "Select the second club", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeamMatches, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text"
                       id="fp-date-time"
                       class="form-control flatpickr-date-time"
                       placeholder="YYYY-MM-DD HH:MM"
                       name="date" />
            </div>
            <br />
            @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.RadioButtonFor(model => model.status, "Postponed") Postponed <br />
                @Html.RadioButtonFor(model => model.status, "Not Started") Not Started <br />
                @Html.RadioButtonFor(model => model.status, "Started") Started <br />
                @Html.RadioButtonFor(model => model.status, "Finished") Finished <br />
                @Html.ValidationMessageFor(model => model.status, "Choose a status", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        $("#fp-date-time").flatpickr({
            enableTime: true,
            dateFormat: "Y-m-d h:i K",
        });

        $(document).ready(function () {
            $('select').on('change', function (event) {
                var prevValue = $(this).data('previous');
                $('select').not(this).find('option[value="' + prevValue + '"]').show();
                var value = $(this).val();
                $(this).data('previous', value);
                $('select').not(this).find('option[value="' + value + '"]').hide();
            });

            $('#league_id').on('change', function () {
                var id = $('#league_id').val();
                document.location.href = "https://localhost:44324/matches/Create/" + id;
            });
        });

    </script>
}

FootballWebApp/Views/matches/Delete.cshtml
@model FootballWebApp.Models.match

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>match</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.team1_score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.team1_score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.team2_score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.team2_score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FootballWebApp/Views/matches/Details.cshtml
@model FootballWebApp.Models.match

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>match</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.team1_score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.team1_score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.team2_score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.team2_score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.match_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FootballWebApp/Views/matches/Edit.cshtml
@model FootballWebApp.Models.match

@{
    ViewBag.Title = "Edit Match";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
}

<h2>Edit Match</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>match</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.match_id)

        <div class="form-group">
            <div class="col-md-10">
                <label>Team 1</label>
                <input disabled type="text" class="form-control" value="@ViewBag.team1.team.name"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Team 2</label>
                <input disabled type="text" class="form-control" value="@ViewBag.team2.team.name" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text"
                       id="fp-date-time"
                       class="form-control flatpickr-date-time"
                       placeholder="YYYY-MM-DD HH:MM"
                       name="date"
                       />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })*@
                
                    @Html.RadioButtonFor(model => model.status, "Postponed", Model.status == "Postponed" ? "checked" : string.Empty) <span>Postponed</span> <br />
                    @Html.RadioButtonFor(model => model.status, "Not Started", Model.status == "Not Started" ? "checked" : string.Empty) <span>Not Started</span> <br />
                    @Html.RadioButtonFor(model => model.status, "Started", Model.status == "Started" ? "checked" : string.Empty) <span>Started</span> <br />
                    @Html.RadioButtonFor(model => model.status, "Finished", Model.status == "Finished" ? "checked" : string.Empty) <span>Finished</span> <br />
                    @Html.ValidationMessageFor(model => model.status, "Choose a status", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        $("#fp-date-time").flatpickr({
            enableTime: true,
            dateFormat: "Y-m-d h:i K",
            defaultDate: "@Model.date"
        });

        $(document).ready(function () {
            $('select').on('change', function (event) {
                var prevValue = $(this).data('previous');
                $('select').not(this).find('option[value="' + prevValue + '"]').show();
                var value = $(this).val();
                $(this).data('previous', value);
                $('select').not(this).find('option[value="' + value + '"]').hide();
            });
        });

    </script>
}

FootballWebApp/Views/matches/Index.cshtml
@model IEnumerable<FootballWebApp.Models.match>


@{
    ViewBag.Title = "Matches";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card mb-4">
    <div class="card-body">
        <section id="row-grouping-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header border-bottom">
                            <h4 class="card-title">Matches Panel</h4>
                        </div>
                        <div class="card-datatable">
                            <table class="dt-row-grouping table">
                                <thead>
                                    <tr>
                                        <th>
                                            Home
                                        </th>
                                        <th>
                                            Away
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.team1_score)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.team2_score)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.date)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.status)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.TeamMatches.First(x => x.match_id == item.match_id && x.home_Away == "home").team.name
                                            </td>
                                            <td>
                                                @item.TeamMatches.Last(x => x.match_id == item.match_id && x.home_Away == "away").team.name
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.team1_score)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.team2_score)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.date)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.status)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { id = item.match_id }) |
                                                @Html.ActionLink("Details", "Details", new { id = item.match_id }) |
                                                @Html.ActionLink("Add Goals", "Create", "goals", new { id = item.match_id }, null) |
                                                @Html.ActionLink("Add Yellow Card", "Create", "yellowcards", new { id = item.match_id }, null) |
                                                @Html.ActionLink("Add Red Card", "Create", "redcards", new { id = item.match_id }, null) |
                                                @Html.ActionLink("Delete", "Delete", new { id = item.match_id })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>

                                        <th>
                                            Home
                                        </th>
                                        <th>
                                            Away
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.team1_score)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.team2_score)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.date)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.status)
                                        </th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>